import { db } from "../db/db";
import { supabase } from "../db/supabase";
import { generateFullLesson, LessonTemplate, AILesson, AILessonBlock, flatLessonToBlocks } from "./geminiService";
import { saveLesson, searchLessons } from "./ragService";
import { aiCrew } from "./aiCrewService";

export const lessonService = {
  fetchOrGenerate: async (
    params: {
      title: string;
      grade: string;
      country: string;
      moduleId: string;
    },
    userId: string
  ): Promise<(AILesson & { id?: string }) | null> => {
    const { title, grade, country, moduleId } = params;

    try {
      // 0. Check local IndexedDB first (skip suggested stubs)
      const localLesson = await db.lessons
        .where("moduleId").equals(moduleId)
        .and(l => l.title === title && l.status !== "suggested")
        .first();

      if (localLesson) {
        return {
          id: localLesson.id,
          title: localLesson.title,
          subtitle: localLesson.subtitle || "",
          blocks: localLesson.blocks || [],
        };
      }

      // 1. Look up module name (needed for subject + generation)
      const { data: moduleData } = await supabase
        .from("modules")
        .select("name")
        .eq("id", moduleId)
        .maybeSingle();

      const subject = moduleData?.name || "General";

      // 2. Check Supabase by exact (title, grade, country) before similarity search
      const { data: exactMatch } = await supabase
        .from("lessons")
        .select("*")
        .eq("lesson_title", title)
        .eq("grade", grade)
        .eq("country", country)
        .maybeSingle();

      let lessonData: LessonTemplate | null = exactMatch as LessonTemplate | null;

      if (!lessonData) {
        // 3. Similarity search with tighter threshold
        const similarLessons = await searchLessons(title, 1);
        if (similarLessons.length > 0 && (similarLessons[0].similarity || 0) > 0.82) {
          lessonData = similarLessons[0];
        }
      }

      if (!lessonData) {
        // 4. Try immediate generation (fast path — uses best available model)
        lessonData = await generateFullLesson(title, country, grade, subject, subject);

        if (lessonData) {
          await saveLesson(lessonData, userId, true);
        } else {
          // 5. Immediate generation failed → hand off to AI Crew
          const taskId = aiCrew.logLessonMiss({ title, grade, subject, country, moduleId, userId });

          // Save a real pending record so PendingLessonView has something to render
          const pendingId = crypto.randomUUID();
          await db.lessons.put({
            id: pendingId,
            moduleId,
            title,
            content: "",
            status: "pending",
            createdAt: Date.now(),
            blocks: [],
            subtitle: "Being generated by AI Crew...",
          });

          return {
            id: pendingId,
            title,
            subtitle: "Being generated by AI Crew...",
            blocks: [],
            _pending: true,
            _taskId: taskId,
          };
        }
      }

      if (!lessonData) return null;

      return buildAILesson(lessonData);
    } catch (error) {
      console.error("Error in lessonService.fetchOrGenerate:", error);
      return null;
    }
  },
};

function buildAILesson(lessonData: LessonTemplate): AILesson & { id?: string } {
  // If the lesson already has structured blocks, use them directly
  if (lessonData.blocks && lessonData.blocks.length > 0) {
    return {
      id: lessonData.id,
      title: lessonData.lesson_title,
      subtitle: `${lessonData.blocks.length} blocks · ~${Math.ceil(lessonData.blocks.length * 1.5)} min`,
      blocks: lessonData.blocks,
    };
  }

  // Legacy fallback: convert flat structure to blocks
  const blocks = flatLessonToBlocks(lessonData);

  return {
    id: lessonData.id,
    title: lessonData.lesson_title,
    subtitle: `${blocks.length} blocks · ~${Math.ceil(blocks.length * 1.5)} min`,
    blocks,
  };
}
