import { db } from "../db/db";
import { supabase } from "../db/supabase";
import { generateFullLesson, LessonTemplate, AILesson, AILessonBlock } from "./geminiService";
import { saveLesson, searchLessons } from "./ragService";
import { aiCrew } from "./aiCrewService";

export const lessonService = {
  fetchOrGenerate: async (
    params: {
      title: string;
      grade: string;
      country: string;
      moduleId: string;
    },
    userId: string
  ): Promise<(AILesson & { id?: string }) | null> => {
    const { title, grade, country, moduleId } = params;

    try {
      // 0. Check local IndexedDB first
      const localLesson = await db.lessons
        .where("moduleId").equals(moduleId)
        .and(l => l.title === title && l.status !== "suggested")
        .first();

      if (localLesson) {
        return {
          id: localLesson.id,
          title: localLesson.title,
          subtitle: localLesson.subtitle || "",
          blocks: localLesson.blocks || [],
        };
      }

      // 1. Search RAG/Supabase
      const similarLessons = await searchLessons(title, 1);
      let lessonData: LessonTemplate | null = null;

      if (similarLessons.length > 0 && (similarLessons[0].similarity || 0) > 0.9) {
        lessonData = similarLessons[0];
      } else {
        // 2. Try immediate generation (fast path — still uses best available model)
        const { data: moduleData } = await supabase
          .from("modules")
          .select("name")
          .eq("id", moduleId)
          .maybeSingle();

        const subject = moduleData?.name || "General";

        lessonData = await generateFullLesson(title, country, grade, subject, subject);

        if (lessonData) {
          await saveLesson(lessonData, userId, true);
        } else {
          // 3. Immediate generation failed → hand off to AI Crew (Pro plans, Gemma 4 generates)
          const taskId = aiCrew.logLessonMiss({ title, grade, subject, country, moduleId, userId });

          // Return a pending stub so the UI shows a generating state instead of an error
          return {
            id: undefined,
            title,
            subtitle: "Being generated by AI Crew...",
            blocks: [],
            _pending: true,
            _taskId: taskId,
          };
        }
      }

      if (!lessonData) return null;

      return buildAILesson(lessonData);
    } catch (error) {
      console.error("Error in lessonService.fetchOrGenerate:", error);
      return null;
    }
  },
};

function buildAILesson(lessonData: LessonTemplate): AILesson & { id?: string } {
  const blocks: AILessonBlock[] = [
    { type: "content", title: "Lesson Content", content: lessonData.content },
  ];

  if (lessonData.exercises?.length > 0) {
    blocks.push({
      type: "examples",
      title: "Exercises",
      examples: lessonData.exercises.map((ex: any) => ({
        question: ex.question,
        steps: [],
        answer: ex.solution,
      })),
    });
  }

  lessonData.quizzes?.forEach((q: any) => {
    blocks.push({
      type: "quiz",
      title: "Quiz",
      quiz: { question: q.question, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation },
    });
  });

  if (lessonData.exam) {
    blocks.push({
      type: "exam",
      title: "Exam Question",
      exam: { source: "National Exam Style", question: lessonData.exam.question, hint: lessonData.exam.hint || "", solution: lessonData.exam.solution },
    });
  }

  return {
    id: lessonData.id,
    title: lessonData.lesson_title,
    subtitle: `${blocks.length} sections · ~15 min`,
    blocks,
  };
}
