import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar' | 'es' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    classrooms: 'Classrooms',
    blueprints: 'Blueprints',
    schedule: 'Schedule',
    progress: 'Progress',
    library: 'Library',
    settings: 'Settings',
    search: 'Search...',
    my_space: 'LevelSpace',
    active_classrooms: 'Active Classrooms',
    learning_stats: 'Learning Stats',
    reminders: 'Reminders',
    agenda: 'Agenda',
    calendar: 'Calendar',
    deep_focus: 'Deep Focus',
    pomodoro_session: 'Pomodoro Session',
    start_focus: 'Start Focus',
    pause: 'Pause',
    explore_modules: 'Explore Modules',
    view_blueprints: 'View Blueprints',
    academic_repository: 'Academic Repository',
    personalized_for: 'Personalized for {grade}',
    your_academic_repository: 'Your Academic Repository.',
    unlock_potential: 'Unlock your',
    achieve_greatness: 'potential.',
    manage: 'Manage',
    no_active_classrooms: 'No active classrooms',
    browse_repository: 'Browse Repository',
    run_audit: 'Run Audit',
    reset: 'Reset',
    preferences: 'Preferences',
    active: 'Active',
    idle: 'Idle',
    modules: 'Modules',
    avg_completion: 'Avg. Completion',
    view_all: 'View All',
    no_pending_reminders: 'No pending reminders.',
    no_upcoming_events: 'No upcoming events.',
    exam: 'Exam',
    controle: 'Controle',
    upcoming_exams: 'Upcoming Exams & Controles',
    add_reminder: 'Add Reminder',
    title: 'Title',
    due_date: 'Due Date',
    type: 'Type',
    assignment: 'Assignment',
    reading: 'Reading',
    quiz: 'Quiz',
    general: 'General',
    curriculum_audit: 'Curriculum Audit',
    ai_auditor: 'AI Auditor',
    audit_description: "We'll analyze your current repository against national standards for {grade} in {country} to identify knowledge gaps.",
    audit_parameters: 'Audit Parameters',
    region: 'Region',
    run_deep_audit: 'Run Deep Audit',
    suggested_units: 'Suggested Module Titles',
    suggested_units_description: "Based on the curriculum for {grade} in {country}, here are some suggested module titles to add to your repository.",
    consulting_resources: 'Consulting pedagogical resources...',
    go_to_classroom: 'Go to Classroom',
    curating_knowledge: 'Curating Knowledge...',
    curating_description: 'Our AI is synthesizing pedagogical structures and national exam requirements to build your personalized module title.',
    synthesizing_blocks: 'Synthesizing Blocks',
    reset_confirm: 'Are you sure you want to reset all data? This cannot be undone.',
    audit_started: "Audit started. We'll notify you of any curriculum gaps.",
    active_paths_desc: 'Your currently selected learning paths.',
    profile_setup: 'Profile Setup',
    personalize_space: 'Personalize your space.',
    setup_progress: 'Setup Progress',
    configure_context: 'Configure your academic context to enable AI-driven curriculum generation from trusted global resources.',
    academic_region: 'Global Success Hub',
    search_countries: 'Search countries...',
    no_countries_found: 'No countries found',
    ai_adapts: 'Select your region to align with world-class standards.',
    academic_level: 'Your Mastery Level',
    learning_interests: 'Learning Interests',
    academic_goal: 'Academic Goal',
    status: 'Status',
    settings_saved: 'Settings Saved',
    pending_changes: 'Pending Changes',
    continue_to_classrooms: 'Continue to Classrooms',
    cancel: 'Cancel',
    profile_updated: 'Profile Updated',
    save_profile: 'Save Profile',
    language: 'Path to Success',
    select_language: 'Choose your language to unlock your full potential and achieve greatness.',
    stem: 'STEM',
    humanities: 'Humanities',
    arts: 'Arts & Design',
    languages: 'Languages',
    tech: 'Technology',
    exam_prep: 'Exam Preparation',
    skill_dev: 'Skill Development',
    general_learning: 'General Learning',
    career_transition: 'Career Transition',
    grade: 'Define your current stage on the path to excellence.',
    select_session_or_subject: 'Select session or subject',
    custom_title: 'Custom Title',
    e_g_math_exam: 'e.g., Math Exam',
    interactive_learning: 'Interactive Learning',
    triple_click_hint: 'Triple-click on white space to trigger AI support.',
    hard_questions: '3 Hard Questions',
    more_examples: 'More Examples',
    exam_questions: 'Exam Questions',
    generating_interactive: 'AI is generating your custom content...',
    interactive_title: 'AI Learning Support',
    interactive_desc: 'Deepen your understanding with custom-generated content.',
    session_settings: 'Session Settings',
    current_session: 'Current Academic Session',
    default_session_duration: 'Default Study Duration',
    minutes: 'minutes',
    e_g_fall_2024: 'e.g., Fall 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Let AI build it for you",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Build it with AI",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
  },
  fr: {
    dashboard: 'Tableau de bord',
    classrooms: 'Salles de classe',
    blueprints: 'Schémas',
    schedule: 'Emploi du temps',
    progress: 'Progrès',
    library: 'Bibliothèque',
    settings: 'Paramètres',
    search: 'Rechercher...',
    my_space: 'Mon Espace',
    active_classrooms: 'Salles actives',
    learning_stats: 'Stats d\'apprentissage',
    reminders: 'Rappels',
    agenda: 'Agenda',
    calendar: 'Calendrier',
    deep_focus: 'Focus Profond',
    pomodoro_session: 'Session Pomodoro',
    start_focus: 'Démarrer le Focus',
    pause: 'Pause',
    explore_modules: 'Explorer les Modules',
    view_blueprints: 'Voir les Schémas',
    academic_repository: 'Répertoire Académique',
    personalized_for: 'Personnalisé pour {grade}',
    your_academic_repository: 'Votre Répertoire Académique.',
    unlock_potential: 'Libérez votre',
    achieve_greatness: 'potentiel.',
    manage: 'Gérer',
    no_active_classrooms: 'Aucune salle active',
    browse_repository: 'Parcourir le Répertoire',
    run_audit: 'Lancer l\'Audit',
    reset: 'Réinitialiser',
    preferences: 'Préférences',
    active: 'Actif',
    idle: 'Inactif',
    modules: 'Modules',
    avg_completion: 'Moy. de complétion',
    view_all: 'Voir tout',
    no_pending_reminders: 'Aucun rappel en attente.',
    no_upcoming_events: 'Aucun événement à venir.',
    exam: 'Examen',
    controle: 'Contrôle',
    upcoming_exams: 'Examens & Contrôles à venir',
    add_reminder: 'Ajouter un rappel',
    title: 'Titre',
    due_date: 'Date d\'échéance',
    type: 'Type',
    assignment: 'Devoir',
    reading: 'Lecture',
    quiz: 'Quiz',
    general: 'Général',
    curriculum_audit: 'Audit du Curriculum',
    ai_auditor: 'Auditeur IA',
    audit_description: "Nous analyserons votre répertoire actuel par rapport aux normes nationales pour {grade} en {country} afin d'identifier les lacunes de connaissances.",
    audit_parameters: 'Paramètres d\'Audit',
    region: 'Région',
    run_deep_audit: 'Lancer l\'Audit Profond',
    suggested_units: 'Titres de Modules Suggérés',
    suggested_units_description: "Sur la base du programme pour {grade} en {country}, voici quelques titres de modules suggérés à ajouter à votre répertoire.",
    consulting_resources: 'Consultation des ressources pédagogiques...',
    go_to_classroom: 'Aller à la salle de classe',
    curating_knowledge: 'Curation des connaissances...',
    curating_description: 'Notre IA synthétise les structures pédagogiques et les exigences des examens nationaux pour construire votre titre de module personnalisé.',
    synthesizing_blocks: 'Synthèse des blocs',
    reset_confirm: 'Êtes-vous sûr de vouloir réinitialiser toutes les données ? Cela ne peut pas être annulé.',
    audit_started: "Audit démarré. Nous vous informerons de toute lacune dans le curriculum.",
    active_paths_desc: 'Vos parcours d\'apprentissage actuellement sélectionnés.',
    profile_setup: 'Configuration du Profil',
    personalize_space: 'Personnalisez votre espace.',
    setup_progress: 'Progression de l\'installation',
    configure_context: 'Configurez votre contexte académique pour permettre la génération de curriculum par IA à partir de ressources mondiales de confiance.',
    academic_region: 'Pôle de Succès Mondial',
    search_countries: 'Rechercher des pays...',
    no_countries_found: 'Aucun pays trouvé',
    ai_adapts: 'Sélectionnez votre région pour vous aligner sur les standards mondiaux.',
    academic_level: 'Votre Niveau de Maîtrise',
    learning_interests: 'Intérêts d\'Apprentissage',
    academic_goal: 'Objectif Académique',
    status: 'Statut',
    settings_saved: 'Paramètres Enregistrés',
    pending_changes: 'Modifications en attente',
    continue_to_classrooms: 'Continuer vers les salles de classe',
    cancel: 'Annuler',
    profile_updated: 'Profil Mis à Jour',
    save_profile: 'Enregistrer le Profil',
    language: 'Chemin vers le Succès',
    select_language: 'Choisissez votre langue pour libérer tout votre potentiel et atteindre l\'excellence.',
    stem: 'STEM',
    humanities: 'Sciences Humaines',
    arts: 'Arts & Design',
    languages: 'Langues',
    tech: 'Technologie',
    exam_prep: 'Préparation aux Examens',
    skill_dev: 'Développement de Compétences',
    general_learning: 'Apprentissage Général',
    career_transition: 'Transition de Carrière',
    grade: 'Définissez votre étape actuelle sur le chemin de l\'excellence.',
    select_session_or_subject: 'Sélectionner une session ou un sujet',
    custom_title: 'Titre personnalisé',
    e_g_math_exam: 'ex: Examen de Maths',
    interactive_learning: 'Apprentissage Interactif',
    triple_click_hint: 'Triple-cliquez sur l\'espace blanc pour déclencher l\'aide IA.',
    hard_questions: '3 Questions Difficiles',
    more_examples: 'Plus d\'Exemples',
    exam_questions: 'Questions d\'Examen',
    generating_interactive: 'L\'IA génère votre contenu personnalisé...',
    interactive_title: 'Support d\'Apprentissage IA',
    interactive_desc: 'Approfondissez votre compréhension avec du contenu généré sur mesure.',
    session_settings: 'Paramètres de Session',
    current_session: 'Session Académique Actuelle',
    default_session_duration: 'Durée d\'Étude par Défaut',
    minutes: 'minutes',
    e_g_fall_2024: 'ex: Automne 2024',
    hero_title: "Arrête de jongler. Construis un système qui fonctionne",
    hero_subtitle: "Ton savoir, enfin organisé",
    hero_cta_primary: "Lance-toi — c'est gratuit",
    hero_cta_secondary: "Laisse l'IA construire pour toi",
    actions_create_levelspace: "Crée ton LevelSpace",
    actions_create_classroom: "Crée une classe",
    actions_generate_ai: "Construis-le avec l'IA",
    actions_track_progress: "Suis ta progression",
    motivation_start_or_stuck: "Commence maintenant. Ne regarde pas en arrière",
    motivation_power: "Ton système. Tes règles",
    onboarding_first_classroom: "Construis ta première classe",
    onboarding_start_building: "Construis ton premier système",
    dashboard_start: "Lance-toi",
    dashboard_continue: "Continue",
    dashboard_explore: "Explore ton espace",
  },
  ar: {
    dashboard: 'لوحة القيادة',
    classrooms: 'الفصول الدراسية',
    blueprints: 'المخططات',
    schedule: 'الجدول الزمني',
    progress: 'التقدم',
    library: 'المكتبة',
    settings: 'الإعدادات',
    search: 'بحث...',
    my_space: 'مساحتي',
    active_classrooms: 'الفصول النشطة',
    learning_stats: 'إحصائيات التعلم',
    reminders: 'التذكيرات',
    agenda: 'الأجندة',
    calendar: 'التقويم',
    deep_focus: 'تركيز عميق',
    pomodoro_session: 'جلسة بومودورو',
    start_focus: 'بدء التركيز',
    pause: 'إيقاف مؤقت',
    explore_modules: 'استكشاف الوحدات',
    view_blueprints: 'عرض المخططات',
    academic_repository: 'المستودع الأكاديمي',
    personalized_for: 'مخصص لـ {grade}',
    your_academic_repository: 'مستودعك الأكاديمي.',
    unlock_potential: 'أطلق العنان',
    achieve_greatness: 'لإمكانياتك.',
    manage: 'إدارة',
    no_active_classrooms: 'لا توجد فصول نشطة',
    browse_repository: 'تصفح المستودع',
    run_audit: 'تشغيل التدقيق',
    reset: 'إعادة تعيين',
    preferences: 'التفضيلات',
    active: 'نشط',
    idle: 'خامل',
    modules: 'الوحدات',
    avg_completion: 'متوسط الإكمال',
    view_all: 'عرض الكل',
    no_pending_reminders: 'لا توجد تذكيرات معلقة.',
    no_upcoming_events: 'لا توجد أحداث قادمة.',
    exam: 'امتحان',
    controle: 'مراقبة',
    upcoming_exams: 'الامتحانات والمراقبات القادمة',
    add_reminder: 'إضافة تذكير',
    title: 'العنوان',
    due_date: 'تاريخ الاستحقاق',
    type: 'النوع',
    assignment: 'مهمة',
    reading: 'قراءة',
    quiz: 'اختبار قصير',
    general: 'عام',
    curriculum_audit: 'تدقيق المنهج',
    ai_auditor: 'مدقق الذكاء الاصطناعي',
    audit_description: "سنقوم بتحليل مستودعك الحالي مقابل المعايير الوطنية لـ {grade} في {country} لتحديد فجوات المعرفة.",
    audit_parameters: 'معايير التدقيق',
    region: 'المنطقة',
    run_deep_audit: 'تشغيل التدقيق العميق',
    suggested_units: 'عناوين المجزوءات المقترحة',
    suggested_units_description: "بناءً على المنهج الدراسي لـ {grade} في {country}، إليك بعض عناوين المجزوءات المقترحة لإضافتها إلى مستودعك.",
    consulting_resources: 'استشارة الموارد التربوية...',
    go_to_classroom: 'الذهاب إلى الفصل الدراسي',
    curating_knowledge: 'تنسيق المعرفة...',
    curating_description: 'يقوم ذكاؤنا الاصطناعي بتوليف الهياكل التربوية ومتطلبات الامتحانات الوطنية لبناء عنوان مجزوءتك المخصصة.',
    synthesizing_blocks: 'توليف الكتل',
    reset_confirm: 'هل أنت متأكد أنك تريد إعادة تعيين جميع البيانات؟ لا يمكن التراجع عن هذا الإجراء.',
    audit_started: "بدأ التدقيق. سنقوم بإخطارك بأي فجوات في المنهج.",
    active_paths_desc: 'مسارات التعلم المختارة حاليًا.',
    profile_setup: 'إعداد الملف الشخصي',
    personalize_space: 'خصص مساحتك.',
    setup_progress: 'تقدم الإعداد',
    configure_context: 'قم بتكوين سياقك الأكاديمي لتمكين توليد المناهج الدراسية المدعومة بالذكاء الاصطناعي من موارد عالمية موثوقة.',
    academic_region: 'مركز النجاح العالمي',
    search_countries: 'البحث عن الدول...',
    no_countries_found: 'لم يتم العثور على دول',
    ai_adapts: 'اختر منطقتك لتتماشى مع المعايير العالمية المتميزة.',
    academic_level: 'مستوى إتقانك',
    learning_interests: 'اهتمامات التعلم',
    academic_goal: 'الهدف الأكاديمي',
    status: 'الحالة',
    settings_saved: 'تم حفظ الإعدادات',
    pending_changes: 'تغييرات معلقة',
    continue_to_classrooms: 'المتابعة إلى الفصول الدراسية',
    cancel: 'إلغاء',
    profile_updated: 'تم تحديث الملف الشخصي',
    save_profile: 'حفظ الملف الشخصي',
    language: 'طريق النجاح',
    select_language: 'اختر لغتك لإطلاق العنان لإمكانياتك الكاملة وتحقيق العظمة.',
    stem: 'العلوم والتكنولوجيا والهندسة والرياضيات',
    humanities: 'العلوم الإنسانية',
    arts: 'الفنون والتصميم',
    languages: 'اللغات',
    tech: 'التكنولوجيا',
    exam_prep: 'التحضير للامتحانات',
    skill_dev: 'تطوير المهارات',
    general_learning: 'التعلم العام',
    career_transition: 'التحول الوظيفي',
    grade: 'حدد مرحلتك الحالية في طريق التميز.',
    select_session_or_subject: 'اختر الجلسة أو الموضوع',
    custom_title: 'عنوان مخصص',
    e_g_math_exam: 'مثال: امتحان الرياضيات',
    interactive_learning: 'التعلم التفاعلي',
    triple_click_hint: 'انقر ثلاث مرات على المساحة البيضاء لتفعيل دعم الذكاء الاصطناعي.',
    hard_questions: '3 أسئلة صعبة',
    more_examples: 'مزيد من الأمثلة',
    exam_questions: 'أسئلة الامتحان',
    generating_interactive: 'يقوم الذكاء الاصطناعي بإنشاء محتواك المخصص...',
    interactive_title: 'دعم التعلم بالذكاء الاصطناعي',
    interactive_desc: 'عمق فهمك بمحتوى تم إنشاؤه خصيصًا لك.',
    session_settings: 'إعدادات الجلسة',
    current_session: 'الفصل الدراسي الحالي',
    default_session_duration: 'مدة الدراسة الافتراضية',
    minutes: 'دقيقة',
    e_g_fall_2024: 'مثال: خريف 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Let AI build it for you",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Build it with AI",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
  },
  es: {
    dashboard: 'Tablero',
    classrooms: 'Aulas',
    blueprints: 'Planos',
    schedule: 'Horario',
    progress: 'Progreso',
    library: 'Biblioteca',
    settings: 'Ajustes',
    search: 'Buscar...',
    my_space: 'Mi Espacio',
    active_classrooms: 'Aulas Activas',
    learning_stats: 'Estadísticas de Aprendizaje',
    reminders: 'Recordatorios',
    agenda: 'Agenda',
    calendar: 'Calendario',
    deep_focus: 'Enfoque Profundo',
    pomodoro_session: 'Sesión Pomodoro',
    start_focus: 'Iniciar Enfoque',
    pause: 'Pausa',
    explore_modules: 'Explorar Módulos',
    view_blueprints: 'Ver Planos',
    academic_repository: 'Repositorio Académico',
    personalized_for: 'Personalizado para {grade}',
    your_academic_repository: 'Tu Repositorio Académico.',
    unlock_potential: 'Desbloquea tu',
    achieve_greatness: 'potencial.',
    manage: 'Gestionar',
    no_active_classrooms: 'No hay aulas activas',
    browse_repository: 'Explorar Repositorio',
    run_audit: 'Ejecutar Auditoría',
    reset: 'Reiniciar',
    preferences: 'Preferencias',
    active: 'Activo',
    idle: 'Inactivo',
    modules: 'Módulos',
    avg_completion: 'Promedio de Completado',
    view_all: 'Ver todo',
    no_pending_reminders: 'No hay recordatorios pendientes.',
    no_upcoming_events: 'No hay eventos próximos.',
    exam: 'Examen',
    controle: 'Control',
    upcoming_exams: 'Próximos Exámenes y Controles',
    add_reminder: 'Agregar Recordatorio',
    title: 'Título',
    due_date: 'Fecha de Vencimiento',
    type: 'Tipo',
    assignment: 'Tarea',
    reading: 'Lectura',
    quiz: 'Cuestionario',
    general: 'General',
    curriculum_audit: 'Auditoría del Currículo',
    ai_auditor: 'Auditor IA',
    audit_description: "Analizaremos tu repositorio actual frente a los estándares nacionales para {grade} en {country} para identificar brechas de conocimiento.",
    audit_parameters: 'Parámetros de Auditoría',
    region: 'Región',
    run_deep_audit: 'Ejecutar Auditoría Profunda',
    suggested_units: 'Títulos de Módulos Sugeridos',
    suggested_units_description: "Basado en el currículo para {grade} en {country}, aquí hay algunos títulos de módulos sugeridos para agregar a tu repositorio.",
    consulting_resources: 'Consultando recursos pedagógicos...',
    go_to_classroom: 'Ir al Aula',
    curating_knowledge: 'Curando conocimiento...',
    curating_description: 'Nuestra IA está sintetizando estructuras pedagógicas y requisitos de exámenes nacionales para construir tu título de módulo personalizado.',
    synthesizing_blocks: 'Sintetizando bloques',
    reset_confirm: '¿Estás seguro de que deseas restablecer todos los datos? Esto no se puede deshacer.',
    audit_started: "Auditoría iniciada. Te notificaremos de cualquier brecha en el currículo.",
    active_paths_desc: 'Tus rutas de aprendizaje seleccionadas actualmente.',
    profile_setup: 'Configuración del Perfil',
    personalize_space: 'Personaliza tu espacio.',
    setup_progress: 'Progreso de la configuración',
    configure_context: 'Configura tu contexto académico para permitir la generación de currículos impulsada por IA a partir de recursos globales confiables.',
    academic_region: 'Centro de Éxito Global',
    search_countries: 'Buscar países...',
    no_countries_found: 'No se encontraron países',
    ai_adapts: 'Selecciona tu región para alinearte con los estándares de clase mundial.',
    academic_level: 'Tu Nivel de Maestría',
    learning_interests: 'Intereses de Aprendizaje',
    academic_goal: 'Meta Académica',
    status: 'Estado',
    settings_saved: 'Ajustes Guardados',
    pending_changes: 'Cambios Pendientes',
    continue_to_classrooms: 'Continuar a las aulas',
    cancel: 'Cancelar',
    profile_updated: 'Perfil Actualizado',
    save_profile: 'Guardar Perfil',
    language: 'Camino al Éxito',
    select_language: 'Elige tu idioma para desbloquear todo tu potencial y alcanzar la grandeza.',
    stem: 'STEM',
    humanities: 'Humanidades',
    arts: 'Artes y Diseño',
    languages: 'Idiomas',
    tech: 'Tecnología',
    exam_prep: 'Preparación para Exámenes',
    skill_dev: 'Desarrollo de Habilidades',
    general_learning: 'Aprendizaje General',
    career_transition: 'Transición de Carrera',
    grade: 'Define tu etapa actual en el camino hacia la excelencia.',
    select_session_or_subject: 'Seleccionar sesión o tema',
    custom_title: 'Título personalizado',
    e_g_math_exam: 'ej: Examen de Matemáticas',
    interactive_learning: 'Aprendizaje Interactivo',
    triple_click_hint: 'Haz triple clic en el espacio en blanco para activar el soporte de IA.',
    hard_questions: '3 Preguntas Difíciles',
    more_examples: 'Más Ejemplos',
    exam_questions: 'Preguntas de Examen',
    generating_interactive: 'La IA está generando tu contenido personalizado...',
    interactive_title: 'Soporte de Aprendizaje IA',
    interactive_desc: 'Profundiza tu comprensión con contenido generado a medida.',
    session_settings: 'Ajustes de Sesión',
    current_session: 'Sesión Académica Actual',
    default_session_duration: 'Duración de Estudio por Defecto',
    minutes: 'minutos',
    e_g_fall_2024: 'ej: Otoño 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Let AI build it for you",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Build it with AI",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
  },
  de: {
    dashboard: 'Dashboard',
    classrooms: 'Klassenzimmer',
    blueprints: 'Entwürfe',
    schedule: 'Zeitplan',
    progress: 'Fortschritt',
    library: 'Bibliothek',
    settings: 'Einstellungen',
    search: 'Suche...',
    my_space: 'Mein Bereich',
    active_classrooms: 'Aktive Klassen',
    learning_stats: 'Lernstatistiken',
    reminders: 'Erinnerungen',
    agenda: 'Agenda',
    calendar: 'Kalender',
    deep_focus: 'Tiefer Fokus',
    pomodoro_session: 'Pomodoro-Sitzung',
    start_focus: 'Fokus starten',
    pause: 'Pause',
    explore_modules: 'Module erkunden',
    view_blueprints: 'Entwürfe anzeigen',
    academic_repository: 'Akademisches Repository',
    personalized_for: 'Personalisiert für {grade}',
    your_academic_repository: 'Dein akademisches Repository.',
    unlock_potential: 'Entfalte dein',
    achieve_greatness: 'Potenzial.',
    manage: 'Verwalten',
    no_active_classrooms: 'Keine aktiven Klassen',
    browse_repository: 'Repository durchsuchen',
    run_audit: 'Audit ausführen',
    reset: 'Zurücksetzen',
    preferences: 'Präferenzen',
    active: 'Aktiv',
    idle: 'Inaktiv',
    modules: 'Module',
    avg_completion: 'Durchschn. Abschluss',
    view_all: 'Alle anzeigen',
    no_pending_reminders: 'Keine anstehenden Erinnerungen.',
    no_upcoming_events: 'Keine anstehenden Ereignisse.',
    exam: 'Prüfung',
    controle: 'Kontrolle',
    upcoming_exams: 'Anstehende Prüfungen & Kontrollen',
    add_reminder: 'Erinnerung hinzufügen',
    title: 'Titel',
    due_date: 'Fälligkeitsdatum',
    type: 'Typ',
    assignment: 'Aufgabe',
    reading: 'Lesen',
    quiz: 'Quiz',
    general: 'Allgemein',
    curriculum_audit: 'Lehrplan-Audit',
    ai_auditor: 'KI-Auditor',
    audit_description: "Wir analysieren Ihr aktuelles Repository anhand nationaler Standards für {grade} in {country}, um Wissenslücken zu identifizieren.",
    audit_parameters: 'Audit-Parameter',
    region: 'Region',
    run_deep_audit: 'Tiefen-Audit ausführen',
    suggested_units: 'Vorgeschlagene Modultitel',
    suggested_units_description: "Basierend auf dem Lehrplan für {grade} in {country} sind hier einige vorgeschlagene Modultitel, die Sie Ihrem Repository hinzufügen können.",
    consulting_resources: 'Pädagogische Ressourcen werden konsultiert...',
    go_to_classroom: 'Zum Klassenzimmer',
    curating_knowledge: 'Wissen kuratieren...',
    curating_description: 'Unsere KI synthetisiert pädagogische Strukturen und nationale Prüfungsanforderungen, um Ihren personalisierten Modultitel zu erstellen.',
    synthesizing_blocks: 'Blöcke werden synthetisiert',
    reset_confirm: 'Sind Sie sicher, dass Sie alle Daten zurücksetzen möchten? Dies kann nicht rückgängig gemacht werden.',
    audit_started: "Audit gestartet. Wir benachrichtigen Sie über etwaige Lehrplanlücken.",
    active_paths_desc: 'Ihre aktuell ausgewählten Lernpfade.',
    profile_setup: 'Profil-Setup',
    personalize_space: 'Personalisiere deinen Bereich.',
    setup_progress: 'Einrichtungsfortschritt',
    configure_context: 'Konfigurieren Sie Ihren akademischen Kontext, um KI-gesteuerte Lehrplangenerierung aus vertrauenswürdigen globalen Ressourcen zu ermöglichen.',
    academic_region: 'Globales Erfolgszentrum',
    search_countries: 'Länder suchen...',
    no_countries_found: 'Keine Länder gefunden',
    ai_adapts: 'Wählen Sie Ihre Region aus, um sich an erstklassigen Standards auszurichten.',
    academic_level: 'Ihre Meisterschaftsstufe',
    learning_interests: 'Lerninteressen',
    academic_goal: 'Akademisches Ziel',
    status: 'Status',
    settings_saved: 'Einstellungen gespeichert',
    pending_changes: 'Ausstehende Änderungen',
    continue_to_classrooms: 'Weiter zu den Klassenzimmern',
    cancel: 'Abbrechen',
    profile_updated: 'Profil aktualisiert',
    save_profile: 'Profil speichern',
    language: 'Weg zum Erfolg',
    select_language: 'Wählen Sie Ihre Sprache, um Ihr volles Potenzial auszuschöpfen und Großes zu erreichen.',
    stem: 'MINT',
    humanities: 'Geisteswissenschaften',
    arts: 'Kunst & Design',
    languages: 'Sprachen',
    tech: 'Technologie',
    exam_prep: 'Prüfungsvorbereitung',
    skill_dev: 'Kompetenzentwicklung',
    general_learning: 'Allgemeines Lernen',
    career_transition: 'Beruflicher Übergang',
    grade: 'Definieren Sie Ihre aktuelle Etappe auf dem Weg zur Exzellenz.',
    select_session_or_subject: 'Sitzung oder Thema auswählen',
    custom_title: 'Benutzerdefinierter Titel',
    e_g_math_exam: 'z.B. Mathe-Prüfung',
    interactive_learning: 'Interaktives Lernen',
    triple_click_hint: 'Dreifachklick auf den Leerraum, um KI-Unterstützung auszulösen.',
    hard_questions: '3 schwere Fragen',
    more_examples: 'Mehr Beispiele',
    exam_questions: 'Prüfungsfragen',
    generating_interactive: 'KI generiert Ihre benutzerdefinierten Inhalte...',
    interactive_title: 'KI-Lernunterstützung',
    interactive_desc: 'Vertiefen Sie Ihr Verständnis mit maßgeschneiderten Inhalten.',
    session_settings: 'Sitzungseinstellungen',
    current_session: 'Aktuelle akademische Sitzung',
    default_session_duration: 'Standard-Studiendauer',
    minutes: 'Minuten',
    e_g_fall_2024: 'z.B. Herbst 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Let AI build it for you",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Build it with AI",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
  }
};

const sharedFallbackTranslations: Record<Language, Record<string, string>> = {
  en: {
    content: 'Content',
    tools: 'Tools',
    logout: 'Logout',
    active_session: 'Active Session',
    back: 'Back',
  },
  fr: {
    content: 'Contenu',
    tools: 'Outils',
    logout: 'DÃ©connexion',
    active_session: 'Session active',
    back: 'Retour',
  },
  ar: {
    content: 'Ø§Ù„Ù…Ø­ØªÙˆÙ‰',
    tools: 'Ø§Ù„Ø£Ø¯ÙˆØ§Øª',
    logout: 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬',
    active_session: 'Ø§Ù„Ø¬Ù„Ø³Ø© Ø§Ù„Ù†Ø´Ø·Ø©',
    back: 'Ø±Ø¬ÙˆØ¹',
  },
  es: {
    content: 'Contenido',
    tools: 'Herramientas',
    logout: 'Cerrar sesiÃ³n',
    active_session: 'SesiÃ³n activa',
    back: 'Volver',
  },
  de: {
    content: 'Inhalte',
    tools: 'Werkzeuge',
    logout: 'Abmelden',
    active_session: 'Aktive Sitzung',
    back: 'ZurÃ¼ck',
  },
};

const uiTranslations: Record<Language, Record<string, string>> = {
  en: {
    profile: 'Profile',
    academic_path: 'Academic Path',
    academic_identity: 'Academic identity',
    academic_identity_desc: 'This keeps the official curriculum accurate. Normal learners should set it during onboarding and use future goals below to personalize AI explanations.',
    locked_after_onboarding: 'Locked after onboarding',
    editable_for_setup: 'Editable for setup',
    country: 'Country',
    not_set: 'Not set',
    track: 'Track',
    section: 'Section',
    international_option: 'International option',
    none: 'None',
    future_goals: 'Future goals',
    future_goals_desc: 'This shapes AI tone, examples, and projects without changing the official curriculum.',
    career_direction: 'Career direction',
    custom_goal: 'Custom goal',
    custom_goal_placeholder: 'Pediatric doctor, civil engineer, product designer...',
    hobbies_interests: 'Hobbies and interests',
    hobbies_placeholder: 'Robotics, football, drawing...',
    add: 'Add',
    learning_style: 'Learning style',
    target_skills: 'Target skills',
    target_skills_placeholder: 'Problem solving, public speaking, writing...',
    preferred_tone: 'Preferred tone',
    explanation_style: 'Explanation style',
    motivation_focus: 'Motivation focus',
    cloud_and_data: 'Cloud and data',
    supabase_connection: 'Supabase connection',
    connected: 'Connected',
    disconnected: 'Disconnected',
    refresh_connection: 'Refresh connection',
    sync_all_data: 'Sync all data',
    synchronizing: 'Synchronizing...',
    ai_provider_api_key: 'AI Provider API Key',
    nvidia_api_key: 'NVIDIA NIM API Key',
    save_key: 'Save Key',
    saved: 'Saved',
    return_to_dashboard: 'Return to Dashboard',
    back_to_dashboard: 'Back to Dashboard',
    classroom_not_found: 'Classroom not found.',
    lesson_not_found: 'Lesson not found.',
    curriculum_topics: 'Curriculum Topics',
    curriculum_units: 'Module Title',
    available_quizzes: 'Available Quizzes',
    lesson_quizzes: 'Lesson Quizzes',
    practice_exercises: 'Practice Exercises',
    no_quizzes_for_lessons: 'No quizzes available for these lessons yet.',
    no_exercises_for_lessons: 'No exercises available for these lessons yet.',
    no_quizzes_for_lesson: 'No quizzes available for this lesson yet.',
    no_exercises_for_lesson: 'No exercises available for this lesson yet.',
    study_domains: 'Study domains',
    all_domains: 'All domains',
    all: 'All',
    lesson_unavailable: 'This lesson is not available to students.',
    lesson_unavailable_desc: 'It is currently blocked by curriculum review rules or has been rejected during validation.',
    complete_lesson: 'Complete Lesson',
    lesson_outline: 'Lesson Outline',
    visible: 'Visible',
    concepts: 'Concepts',
    interactive: 'Interactive',
    practice_test: 'Practice Test',
    your_score: 'Your Score',
    show_hint: 'Show Hint',
    hint_shown: 'Hint Shown',
    reveal_solution: 'Reveal Solution',
    pedagogical_hint: 'Pedagogical Hint',
    detailed_solution: 'Detailed Solution',
    exam_challenge: 'Exam Challenge',
    practice_exercise: 'Practice Exercise',
    source: 'Source',
    correct: 'Correct!',
    answer_key_explanation: 'Answer Key & Explanation',
    correct_answer_is: 'The correct answer is:',
    quizzes_ai_generation_hint: 'You can trigger AI generation or load certified modules to populate interactive quizzes.',
    exercises_ai_generation_hint: 'You can trigger AI generation or load certified modules to populate interactive practice tasks.',
    previous: 'Previous',
    next: 'Next',
    continue: 'Continue',
    complete: 'Complete',
  },
  fr: {
    profile: 'Profil',
    academic_path: 'Parcours scolaire',
    academic_identity: 'Identite scolaire',
    academic_identity_desc: 'Cela garde le programme officiel exact. Les eleves doivent le definir pendant l accueil, puis utiliser les objectifs pour personnaliser les explications IA.',
    locked_after_onboarding: 'Verrouille apres l accueil',
    editable_for_setup: 'Modifiable pendant la configuration',
    country: 'Pays',
    not_set: 'Non defini',
    track: 'Filiere',
    section: 'Section',
    international_option: 'Option internationale',
    none: 'Aucune',
    future_goals: 'Objectifs futurs',
    future_goals_desc: 'Cela adapte le ton de l IA, les exemples et les projets sans changer le programme officiel.',
    career_direction: 'Orientation professionnelle',
    custom_goal: 'Objectif personnalise',
    custom_goal_placeholder: 'Medecin pediatre, ingenieur civil, designer produit...',
    hobbies_interests: 'Loisirs et interets',
    hobbies_placeholder: 'Robotique, football, dessin...',
    add: 'Ajouter',
    learning_style: 'Style d apprentissage',
    target_skills: 'Competences visees',
    target_skills_placeholder: 'Resolution de problemes, prise de parole, redaction...',
    preferred_tone: 'Ton prefere',
    explanation_style: 'Style d explication',
    motivation_focus: 'Axe de motivation',
    cloud_and_data: 'Cloud et donnees',
    supabase_connection: 'Connexion Supabase',
    connected: 'Connecte',
    disconnected: 'Deconnecte',
    refresh_connection: 'Actualiser la connexion',
    sync_all_data: 'Synchroniser les donnees',
    synchronizing: 'Synchronisation...',
    ai_provider_api_key: 'Cle API du fournisseur IA',
    nvidia_api_key: 'Cle API NVIDIA NIM',
    save_key: 'Enregistrer la cle',
    saved: 'Enregistre',
    return_to_dashboard: 'Retour au tableau de bord',
    back_to_dashboard: 'Retour au tableau de bord',
    classroom_not_found: 'Salle de classe introuvable.',
    lesson_not_found: 'Lecon introuvable.',
    curriculum_topics: 'Themes du programme',
    curriculum_units: 'Titre du module',
    available_quizzes: 'Quiz disponibles',
    lesson_quizzes: 'Quiz de la lecon',
    practice_exercises: 'Exercices d entrainement',
    no_quizzes_for_lessons: 'Aucun quiz disponible pour ces lecons.',
    no_exercises_for_lessons: 'Aucun exercice disponible pour ces lecons.',
    no_quizzes_for_lesson: 'Aucun quiz disponible pour cette lecon.',
    no_exercises_for_lesson: 'Aucun exercice disponible pour cette lecon.',
    study_domains: 'Domaines d etude',
    all_domains: 'Tous les domaines',
    all: 'Tous',
    lesson_unavailable: 'Cette lecon n est pas disponible pour les eleves.',
    lesson_unavailable_desc: 'Elle est bloquee par les regles de validation du programme ou a ete rejetee.',
    complete_lesson: 'Terminer la lecon',
    lesson_outline: 'Plan de la lecon',
    visible: 'Visible',
    concepts: 'Concepts',
    interactive: 'Interactif',
    practice_test: "Test d'entraînement",
    your_score: 'Votre score',
    show_hint: "Afficher l'indice",
    hint_shown: 'Indice affiché',
    reveal_solution: 'Révéler la solution',
    pedagogical_hint: 'Indice pédagogique',
    detailed_solution: 'Solution détaillée',
    exam_challenge: "Défi d'examen",
    practice_exercise: "Exercice d'entraînement",
    source: 'Source',
    correct: 'Correct !',
    answer_key_explanation: 'Corrigé et explication',
    correct_answer_is: 'La bonne réponse est :',
    quizzes_ai_generation_hint: 'Vous pouvez lancer la génération par IA ou charger des modules certifiés pour peupler les quiz interactifs.',
    exercises_ai_generation_hint: "Vous pouvez lancer la génération par IA ou charger des modules certifiés pour peupler les exercices d'entraînement interactifs.",
    previous: 'Précédent',
    next: 'Suivant',
    continue: 'Continuer',
    complete: 'Terminer',
  },
  ar: {
    profile: 'الملف الشخصي',
    academic_path: 'المسار الدراسي',
    academic_identity: 'الهوية الدراسية',
    academic_identity_desc: 'يحافظ هذا على دقة المنهاج الرسمي. يحدده المتعلم أثناء البداية ثم يستخدم الأهداف لتخصيص شرح الذكاء الاصطناعي.',
    locked_after_onboarding: 'مقفل بعد الإعداد الأولي',
    editable_for_setup: 'قابل للتعديل أثناء الإعداد',
    country: 'البلد',
    not_set: 'غير محدد',
    track: 'المسار',
    section: 'الشعبة',
    international_option: 'الخيار الدولي',
    none: 'لا شيء',
    future_goals: 'الأهداف المستقبلية',
    future_goals_desc: 'هذا يوجه نبرة الذكاء الاصطناعي والأمثلة والمشاريع دون تغيير المنهاج الرسمي.',
    career_direction: 'الاتجاه المهني',
    custom_goal: 'هدف مخصص',
    custom_goal_placeholder: 'طبيب أطفال، مهندس مدني، مصمم منتجات...',
    hobbies_interests: 'الهوايات والاهتمامات',
    hobbies_placeholder: 'الروبوتيك، كرة القدم، الرسم...',
    add: 'إضافة',
    learning_style: 'أسلوب التعلم',
    target_skills: 'المهارات المستهدفة',
    target_skills_placeholder: 'حل المشكلات، التحدث أمام الجمهور، الكتابة...',
    preferred_tone: 'النبرة المفضلة',
    explanation_style: 'أسلوب الشرح',
    motivation_focus: 'محور التحفيز',
    cloud_and_data: 'السحابة والبيانات',
    supabase_connection: 'اتصال Supabase',
    connected: 'متصل',
    disconnected: 'غير متصل',
    refresh_connection: 'تحديث الاتصال',
    sync_all_data: 'مزامنة كل البيانات',
    synchronizing: 'جار المزامنة...',
    ai_provider_api_key: 'مفتاح واجهة الذكاء الاصطناعي',
    nvidia_api_key: 'مفتاح NVIDIA NIM',
    save_key: 'حفظ المفتاح',
    saved: 'تم الحفظ',
    return_to_dashboard: 'العودة إلى لوحة التحكم',
    back_to_dashboard: 'العودة إلى لوحة التحكم',
    classroom_not_found: 'لم يتم العثور على الفصل.',
    lesson_not_found: 'لم يتم العثور على الدرس.',
    curriculum_topics: 'مواضيع المنهاج',
    curriculum_units: 'عنوان المجزوءة',
    available_quizzes: 'اختبارات متاحة',
    lesson_quizzes: 'اختبارات الدرس',
    practice_exercises: 'تمارين تطبيقية',
    no_quizzes_for_lessons: 'لا توجد اختبارات لهذه الدروس بعد.',
    no_exercises_for_lessons: 'لا توجد تمارين لهذه الدروس بعد.',
    no_quizzes_for_lesson: 'لا توجد اختبارات لهذا الدرس بعد.',
    no_exercises_for_lesson: 'لا توجد تمارين لهذا الدرس بعد.',
    study_domains: 'مجالات الدراسة',
    all_domains: 'كل المجالات',
    all: 'الكل',
    lesson_unavailable: 'هذا الدرس غير متاح للمتعلمين.',
    lesson_unavailable_desc: 'هو محجوب بسبب قواعد مراجعة المنهاج أو تم رفضه أثناء التحقق.',
    complete_lesson: 'إكمال الدرس',
    lesson_outline: 'خطة الدرس',
    visible: 'ظاهر',
    concepts: 'المفاهيم',
    interactive: 'تفاعلي',
    practice_test: 'اختبار تجريبي',
    your_score: 'درجتك',
    show_hint: 'إظهار التلميح',
    hint_shown: 'تم إظهار التلميح',
    reveal_solution: 'كشف الحل',
    pedagogical_hint: 'تلميح بيداغوجي',
    detailed_solution: 'حل مفصل',
    exam_challenge: 'تحدي الامتحان',
    practice_exercise: 'تمرين تطبيقي',
    source: 'المصدر',
    correct: 'صحيح!',
    answer_key_explanation: 'مفتاح الحل والشرح',
    correct_answer_is: 'الإجابة الصحيحة هي:',
    quizzes_ai_generation_hint: 'يمكنك تشغيل توليد الذكاء الاصطناعي أو تحميل مجزوءات معتمدة لملء الاختبارات التفاعلية.',
    exercises_ai_generation_hint: 'يمكنك تشغيل توليد الذكاء الاصطناعي أو تحميل مجزوءات معتمدة لملء التمارين التطبيقية التفاعلية.',
    previous: 'السابق',
    next: 'التالي',
    continue: 'متابعة',
    complete: 'إكمال',
  },
  es: {
    profile: 'Perfil',
    academic_path: 'Ruta academica',
    academic_identity: 'Identidad academica',
    academic_identity_desc: 'Mantiene preciso el curriculo oficial. Los estudiantes deben definirlo durante la bienvenida y usar metas futuras para personalizar la IA.',
    locked_after_onboarding: 'Bloqueado despues de la bienvenida',
    editable_for_setup: 'Editable durante la configuracion',
    country: 'Pais',
    not_set: 'Sin definir',
    track: 'Itinerario',
    section: 'Seccion',
    international_option: 'Opcion internacional',
    none: 'Ninguna',
    future_goals: 'Metas futuras',
    future_goals_desc: 'Esto ajusta el tono, ejemplos y proyectos de la IA sin cambiar el curriculo oficial.',
    career_direction: 'Direccion profesional',
    custom_goal: 'Meta personalizada',
    custom_goal_placeholder: 'Pediatra, ingeniero civil, disenador de producto...',
    hobbies_interests: 'Aficiones e intereses',
    hobbies_placeholder: 'Robotica, futbol, dibujo...',
    add: 'Anadir',
    learning_style: 'Estilo de aprendizaje',
    target_skills: 'Habilidades objetivo',
    target_skills_placeholder: 'Resolucion de problemas, oratoria, escritura...',
    preferred_tone: 'Tono preferido',
    explanation_style: 'Estilo de explicacion',
    motivation_focus: 'Enfoque de motivacion',
    cloud_and_data: 'Nube y datos',
    supabase_connection: 'Conexion Supabase',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    refresh_connection: 'Actualizar conexion',
    sync_all_data: 'Sincronizar datos',
    synchronizing: 'Sincronizando...',
    ai_provider_api_key: 'Clave API de IA',
    nvidia_api_key: 'Clave API NVIDIA NIM',
    save_key: 'Guardar clave',
    saved: 'Guardado',
    return_to_dashboard: 'Volver al panel',
    back_to_dashboard: 'Volver al panel',
    classroom_not_found: 'Aula no encontrada.',
    lesson_not_found: 'Leccion no encontrada.',
    curriculum_topics: 'Temas del curriculo',
    curriculum_units: 'Título del módulo',
    available_quizzes: 'Cuestionarios disponibles',
    lesson_quizzes: 'Cuestionarios de la leccion',
    practice_exercises: 'Ejercicios practicos',
    no_quizzes_for_lessons: 'Aun no hay cuestionarios para estas lecciones.',
    no_exercises_for_lessons: 'Aun no hay ejercicios para estas lecciones.',
    no_quizzes_for_lesson: 'Aun no hay cuestionarios para esta leccion.',
    no_exercises_for_lesson: 'Aun no hay ejercicios para esta leccion.',
    study_domains: 'Dominios de estudio',
    all_domains: 'Todos los dominios',
    all: 'Todo',
    lesson_unavailable: 'Esta leccion no esta disponible para estudiantes.',
    lesson_unavailable_desc: 'Esta bloqueada por revision curricular o fue rechazada.',
    complete_lesson: 'Completar leccion',
    lesson_outline: 'Esquema de la leccion',
    visible: 'Visible',
    concepts: 'Conceptos',
    interactive: 'Interactivo',
    practice_test: 'Prueba de práctica',
    your_score: 'Tu puntuación',
    show_hint: 'Mostrar pista',
    hint_shown: 'Pista mostrada',
    reveal_solution: 'Revelar solución',
    pedagogical_hint: 'Pista pedagógica',
    detailed_solution: 'Solución detallada',
    exam_challenge: 'Desafío de examen',
    practice_exercise: 'Ejercicio de práctica',
    source: 'Fuente',
    correct: '¡Correcto!',
    answer_key_explanation: 'Clave de respuestas y explicación',
    correct_answer_is: 'La respuesta correcta es:',
    quizzes_ai_generation_hint: 'Puede activar la generación de IA o cargar módulos certificados para completar cuestionarios interactivos.',
    exercises_ai_generation_hint: 'Puede activar la generación de IA o cargar módulos certificados para completar tareas prácticas interactivas.',
    previous: 'Anterior',
    next: 'Siguiente',
    continue: 'Continuar',
    complete: 'Completar',
  },
  de: {
    profile: 'Profil',
    academic_path: 'Akademischer Pfad',
    academic_identity: 'Akademische Identitaet',
    academic_identity_desc: 'Dies haelt den offiziellen Lehrplan korrekt. Lernende legen es beim Onboarding fest und nutzen Ziele zur KI-Personalisierung.',
    locked_after_onboarding: 'Nach Onboarding gesperrt',
    editable_for_setup: 'Fuer Einrichtung bearbeitbar',
    country: 'Land',
    not_set: 'Nicht festgelegt',
    track: 'Schwerpunkt',
    section: 'Sektion',
    international_option: 'Internationale Option',
    none: 'Keine',
    future_goals: 'Zukunftsziele',
    future_goals_desc: 'Dies praegt KI-Ton, Beispiele und Projekte, ohne den offiziellen Lehrplan zu aendern.',
    career_direction: 'Berufsrichtung',
    custom_goal: 'Eigenes Ziel',
    custom_goal_placeholder: 'Kinderarzt, Bauingenieur, Produktdesigner...',
    hobbies_interests: 'Hobbys und Interessen',
    hobbies_placeholder: 'Robotik, Fussball, Zeichnen...',
    add: 'Hinzufuegen',
    learning_style: 'Lernstil',
    target_skills: 'Zielfaehigkeiten',
    target_skills_placeholder: 'Problemloesen, Praesentieren, Schreiben...',
    preferred_tone: 'Bevorzugter Ton',
    explanation_style: 'Erklaerstil',
    motivation_focus: 'Motivationsfokus',
    cloud_and_data: 'Cloud und Daten',
    supabase_connection: 'Supabase-Verbindung',
    connected: 'Verbunden',
    disconnected: 'Getrennt',
    refresh_connection: 'Verbindung aktualisieren',
    sync_all_data: 'Alle Daten synchronisieren',
    synchronizing: 'Synchronisiere...',
    ai_provider_api_key: 'KI-Anbieter API-Schluessel',
    nvidia_api_key: 'NVIDIA NIM API-Schluessel',
    save_key: 'Schluessel speichern',
    saved: 'Gespeichert',
    return_to_dashboard: 'Zurueck zum Dashboard',
    back_to_dashboard: 'Zurueck zum Dashboard',
    classroom_not_found: 'Klassenzimmer nicht gefunden.',
    lesson_not_found: 'Lektion nicht gefunden.',
    curriculum_topics: 'Lehrplanthemen',
    curriculum_units: 'Modultitel',
    available_quizzes: 'Verfuegbare Quizze',
    lesson_quizzes: 'Lektionsquizze',
    practice_exercises: 'Uebungsaufgaben',
    no_quizzes_for_lessons: 'Fuer diese Lektionen gibt es noch keine Quizze.',
    no_exercises_for_lessons: 'Fuer diese Lektionen gibt es noch keine Uebungen.',
    no_quizzes_for_lesson: 'Fuer diese Lektion gibt es noch kein Quiz.',
    no_exercises_for_lesson: 'Fuer diese Lektion gibt es noch keine Uebungen.',
    study_domains: 'Lernbereiche',
    all_domains: 'Alle Bereiche',
    all: 'Alle',
    lesson_unavailable: 'Diese Lektion ist fuer Lernende nicht verfuegbar.',
    lesson_unavailable_desc: 'Sie ist durch Lehrplanpruefung gesperrt oder wurde bei der Validierung abgelehnt.',
    complete_lesson: 'Lektion abschliessen',
    lesson_outline: 'Lektionsuebersicht',
    visible: 'Sichtbar',
    concepts: 'Konzepte',
    interactive: 'Interaktiv',
    practice_test: 'Übungstest',
    your_score: 'Deine Punktzahl',
    show_hint: 'Hinweis anzeigen',
    hint_shown: 'Hinweis angezeigt',
    reveal_solution: 'Lösung enthüllen',
    pedagogical_hint: 'Pädagogischer Hinweis',
    detailed_solution: 'Detaillierte Lösung',
    exam_challenge: 'Prüfungsherausforderung',
    practice_exercise: 'Übungsaufgabe',
    source: 'Quelle',
    correct: 'Richtig!',
    answer_key_explanation: 'Antwortschlüssel & Erklärung',
    correct_answer_is: 'Die richtige Antwort ist:',
    quizzes_ai_generation_hint: 'Sie können die KI-Generierung auslösen oder zertifizierte Module laden, um interaktive Quizze zu füllen.',
    exercises_ai_generation_hint: 'Sie können die KI-Generierung auslösen oder zertifizierte Module laden, um interaktive Übungsaufgaben zu füllen.',
    previous: 'Zurück',
    next: 'Weiter',
    continue: 'Weiter',
    complete: 'Abschließen',
  },
};

const uiExtensionTranslations: Partial<Record<Language, Record<string, string>>> = {
  en: {
    locked_academic_desc: 'Academic country, grade, and track are locked after onboarding so the official curriculum cannot drift. Future goals stay editable for personalization.',
    learning_style_desc: 'Choose how LevelSpace should explain, practice, and motivate.',
    cloud_and_data_desc: 'Sync your work across devices without treating this page like a database reset.',
    status: 'Status',
    configure_study_defaults: 'Configure study session defaults',
    ai_provider_api_key_desc: 'Configure your AI key; classroom content works without one.',
    stored_locally: 'Stored locally in your browser; never sent to our servers.',
    nvidia_api_key_desc: 'Admin AI features only; Gemma 3 27B via server proxy.',
    nvidia_api_key_help: 'Used for admin bulk generation. Model: google/gemma-3-27b-it. Get a free key at build.nvidia.com.',
    supabase_cloud_sync: 'Supabase Cloud Sync',
    supabase_cloud_sync_desc: 'Connect to your own database for cross-device sync.',
    local_only_mode: 'Local-Only Mode',
    supabase_not_configured: 'Supabase is not configured',
    supabase_not_configured_desc: 'To enable cloud sync and real-time features, provide your Supabase credentials in the Secrets panel of AI Studio.',
    refresh_connection_status: 'Refresh Connection Status',
    connection_active: 'Connection Active',
    data_syncing_supabase: 'Your data is being synced to your Supabase instance.',
    lessons: 'Lessons',
    quizzes: 'Quizzes',
    exercises: 'Exercises',
  },
  fr: {
    locked_academic_desc: 'Le pays, le niveau et la filiere sont verrouilles apres l accueil afin de garder le programme officiel stable. Les objectifs restent modifiables.',
    learning_style_desc: 'Choisissez comment LevelSpace doit expliquer, entrainer et motiver.',
    cloud_and_data_desc: 'Synchronisez votre travail entre appareils sans reinitialiser vos donnees.',
    status: 'Statut',
    configure_study_defaults: 'Configurer les valeurs par defaut des sessions',
    ai_provider_api_key_desc: 'Configurez votre cle IA; le contenu de classe fonctionne sans elle.',
    stored_locally: 'Stocke localement dans votre navigateur; jamais envoye a nos serveurs.',
    nvidia_api_key_desc: 'Fonctions IA admin uniquement; Gemma 3 27B via proxy serveur.',
    nvidia_api_key_help: 'Utilise pour la generation admin en masse. Modele: google/gemma-3-27b-it. Cle gratuite sur build.nvidia.com.',
    supabase_cloud_sync: 'Synchronisation cloud Supabase',
    supabase_cloud_sync_desc: 'Connectez votre base de donnees pour la synchronisation multi-appareils.',
    local_only_mode: 'Mode local uniquement',
    supabase_not_configured: 'Supabase n est pas configure',
    supabase_not_configured_desc: 'Pour activer la synchronisation cloud et le temps reel, ajoutez vos identifiants Supabase dans le panneau Secrets de AI Studio.',
    refresh_connection_status: 'Actualiser le statut de connexion',
    connection_active: 'Connexion active',
    data_syncing_supabase: 'Vos donnees sont synchronisees vers votre instance Supabase.',
    lessons: 'Lecons',
    quizzes: 'Quiz',
    exercises: 'Exercices',
  },
  es: {
    locked_academic_desc: 'Pais, grado e itinerario quedan bloqueados despues de la bienvenida para mantener estable el curriculo oficial. Las metas siguen editables.',
    learning_style_desc: 'Elige como LevelSpace debe explicar, practicar y motivar.',
    cloud_and_data_desc: 'Sincroniza tu trabajo entre dispositivos sin reiniciar tus datos.',
    status: 'Estado',
    configure_study_defaults: 'Configurar valores predeterminados de estudio',
    ai_provider_api_key_desc: 'Configura tu clave de IA; el contenido del aula funciona sin ella.',
    stored_locally: 'Guardado localmente en tu navegador; nunca se envia a nuestros servidores.',
    nvidia_api_key_desc: 'Funciones IA de administrador solamente; Gemma 3 27B via proxy del servidor.',
    nvidia_api_key_help: 'Usado para generacion masiva de administrador. Modelo: google/gemma-3-27b-it. Clave gratis en build.nvidia.com.',
    supabase_cloud_sync: 'Sincronizacion cloud Supabase',
    supabase_cloud_sync_desc: 'Conecta tu propia base de datos para sincronizar entre dispositivos.',
    local_only_mode: 'Modo solo local',
    supabase_not_configured: 'Supabase no esta configurado',
    supabase_not_configured_desc: 'Para activar sincronizacion cloud y tiempo real, agrega tus credenciales Supabase en el panel Secrets de AI Studio.',
    refresh_connection_status: 'Actualizar estado de conexion',
    connection_active: 'Conexion activa',
    data_syncing_supabase: 'Tus datos se estan sincronizando con tu instancia Supabase.',
    lessons: 'Lecciones',
    quizzes: 'Cuestionarios',
    exercises: 'Ejercicios',
  },
  de: {
    locked_academic_desc: 'Land, Klasse und Schwerpunkt bleiben nach dem Onboarding gesperrt, damit der offizielle Lehrplan stabil bleibt. Ziele bleiben bearbeitbar.',
    learning_style_desc: 'Waehle, wie LevelSpace erklaeren, ueben und motivieren soll.',
    cloud_and_data_desc: 'Synchronisiere deine Arbeit geraeteuebergreifend, ohne Daten zurueckzusetzen.',
    status: 'Status',
    configure_study_defaults: 'Standardwerte fuer Lernsitzungen einrichten',
    ai_provider_api_key_desc: 'Richte deinen KI-Schluessel ein; Klasseninhalte funktionieren auch ohne ihn.',
    stored_locally: 'Lokal in deinem Browser gespeichert; nie an unsere Server gesendet.',
    nvidia_api_key_desc: 'Nur Admin-KI-Funktionen; Gemma 3 27B ueber Server-Proxy.',
    nvidia_api_key_help: 'Fuer Admin-Massengenerierung. Modell: google/gemma-3-27b-it. Kostenloser Schluessel auf build.nvidia.com.',
    supabase_cloud_sync: 'Supabase Cloud Sync',
    supabase_cloud_sync_desc: 'Verbinde deine eigene Datenbank fuer Synchronisierung zwischen Geraeten.',
    local_only_mode: 'Nur lokaler Modus',
    supabase_not_configured: 'Supabase ist nicht konfiguriert',
    supabase_not_configured_desc: 'Fuer Cloud-Sync und Echtzeitfunktionen fuege deine Supabase-Zugangsdaten im Secrets-Panel von AI Studio hinzu.',
    refresh_connection_status: 'Verbindungsstatus aktualisieren',
    connection_active: 'Verbindung aktiv',
    data_syncing_supabase: 'Deine Daten werden mit deiner Supabase-Instanz synchronisiert.',
    lessons: 'Lektionen',
    quizzes: 'Quizze',
    exercises: 'Uebungen',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language][key] || uiTranslations[language]?.[key] || uiExtensionTranslations[language]?.[key] || uiExtensionTranslations.en?.[key] || sharedFallbackTranslations[language]?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
