import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar' | 'es' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    classrooms: 'Classrooms',
    blueprints: 'Blueprints',
    schedule: 'Schedule',
    progress: 'Progress',
    library: 'Library',
    settings: 'Settings',
    search: 'Search...',
    my_space: 'LevelSpace',
    active_classrooms: 'Active Classrooms',
    learning_stats: 'Learning Stats',
    reminders: 'Reminders',
    agenda: 'Agenda',
    calendar: 'Calendar',
    deep_focus: 'Deep Focus',
    pomodoro_session: 'Pomodoro Session',
    start_focus: 'Start Focus',
    pause: 'Pause',
    explore_modules: 'Explore Modules',
    view_blueprints: 'View Blueprints',
    academic_repository: 'Academic Repository',
    personalized_for: 'Personalized for {grade}',
    your_academic_repository: 'Your Academic Repository.',
    unlock_potential: 'Unlock your',
    achieve_greatness: 'potential.',
    manage: 'Manage',
    no_active_classrooms: 'No active classrooms',
    browse_repository: 'Browse Repository',
    run_audit: 'Run Audit',
    reset: 'Reset',
    preferences: 'Preferences',
    active: 'Active',
    idle: 'Idle',
    modules: 'Modules',
    avg_completion: 'Avg. Completion',
    view_all: 'View All',
    no_pending_reminders: 'No pending reminders.',
    no_upcoming_events: 'No upcoming events.',
    exam: 'Exam',
    controle: 'Controle',
    upcoming_exams: 'Upcoming Exams & Controles',
    add_reminder: 'Add Reminder',
    title: 'Title',
    due_date: 'Due Date',
    type: 'Type',
    assignment: 'Assignment',
    reading: 'Reading',
    quiz: 'Quiz',
    general: 'General',
    curriculum_audit: 'Curriculum Audit',
    ai_auditor: 'Curriculum Auditor',
    audit_description: "We'll analyze your current repository against national standards for {grade} in {country} to identify knowledge gaps.",
    audit_parameters: 'Audit Parameters',
    region: 'Region',
    run_deep_audit: 'Run Deep Audit',
    suggested_units: 'Suggested Units',
    suggested_units_description: "Based on the curriculum for {grade} in {country}, here are some suggested units to add to your repository.",
    consulting_resources: 'Consulting pedagogical resources...',
    go_to_classroom: 'Go to Classroom',
    curating_knowledge: 'Curating Knowledge...',
    curating_description: 'We are preparing your unit using curriculum standards and validated sources.',
    synthesizing_blocks: 'Synthesizing Blocks',
    reset_confirm: 'Are you sure you want to reset all data? This cannot be undone.',
    audit_started: "Audit started. We'll notify you of any curriculum gaps.",
    active_paths_desc: 'Your currently selected learning paths.',
    profile_setup: 'Profile Setup',
    personalize_space: 'Personalize your space.',
    setup_progress: 'Setup Progress',
    configure_context: 'Configure your academic context to prepare curriculum-aligned content from trusted resources.',
    academic_region: 'Global Success Hub',
    search_countries: 'Search countries...',
    no_countries_found: 'No countries found',
    ai_adapts: 'Select your region to align with world-class standards.',
    academic_level: 'Your Mastery Level',
    learning_interests: 'Learning Interests',
    academic_goal: 'Academic Goal',
    status: 'Status',
    settings_saved: 'Settings Saved',
    pending_changes: 'Pending Changes',
    continue_to_classrooms: 'Continue to Classrooms',
    cancel: 'Cancel',
    profile_updated: 'Profile Updated',
    save_profile: 'Save Profile',
    language: 'Path to Success',
    select_language: 'Choose your language to unlock your full potential and achieve greatness.',
    stem: 'STEM',
    humanities: 'Humanities',
    arts: 'Arts & Design',
    languages: 'Languages',
    tech: 'Technology',
    exam_prep: 'Exam Preparation',
    skill_dev: 'Skill Development',
    general_learning: 'General Learning',
    career_transition: 'Career Transition',
    grade: 'Define your current stage on the path to excellence.',
    select_session_or_subject: 'Select session or subject',
    custom_title: 'Custom Title',
    e_g_math_exam: 'e.g., Math Exam',
    interactive_learning: 'Interactive Learning',
    triple_click_hint: 'Triple-click on white space to open guided support.',
    hard_questions: '3 Hard Questions',
    more_examples: 'More Examples',
    exam_questions: 'Exam Questions',
    generating_interactive: 'Preparing your custom content...',
    interactive_title: 'Learning Support',
    interactive_desc: 'Deepen your understanding with custom-generated content.',
    session_settings: 'Session Settings',
    current_session: 'Current Academic Session',
    default_session_duration: 'Default Study Duration',
    minutes: 'minutes',
    e_g_fall_2024: 'e.g., Fall 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Use guided setup",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Use guided setup",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
    loading: 'Loading…',
    classroom_not_found: 'Classroom not found.',
    classroom_empty_description: 'Load lessons from Supabase or use guided suggestions.',
    classroom_ai_suggestions: 'Guided suggestions',
  },
  fr: {
    dashboard: 'Tableau de bord',
    classrooms: 'Salles de classe',
    blueprints: 'Schémas',
    schedule: 'Emploi du temps',
    progress: 'Progrès',
    library: 'Bibliothèque',
    settings: 'Paramètres',
    search: 'Rechercher...',
    my_space: 'Mon Espace',
    active_classrooms: 'Salles actives',
    learning_stats: 'Stats d\'apprentissage',
    reminders: 'Rappels',
    agenda: 'Agenda',
    calendar: 'Calendrier',
    deep_focus: 'Focus Profond',
    pomodoro_session: 'Session Pomodoro',
    start_focus: 'Démarrer le Focus',
    pause: 'Pause',
    explore_modules: 'Explorer les Modules',
    view_blueprints: 'Voir les Schémas',
    academic_repository: 'Répertoire Académique',
    personalized_for: 'Personnalisé pour {grade}',
    your_academic_repository: 'Votre Répertoire Académique.',
    unlock_potential: 'Libérez votre',
    achieve_greatness: 'potentiel.',
    manage: 'Gérer',
    no_active_classrooms: 'Aucune salle active',
    browse_repository: 'Parcourir le Répertoire',
    run_audit: 'Lancer l\'Audit',
    reset: 'Réinitialiser',
    preferences: 'Préférences',
    active: 'Actif',
    idle: 'Inactif',
    modules: 'Modules',
    avg_completion: 'Moy. de complétion',
    view_all: 'Voir tout',
    no_pending_reminders: 'Aucun rappel en attente.',
    no_upcoming_events: 'Aucun événement à venir.',
    exam: 'Examen',
    controle: 'Contrôle',
    upcoming_exams: 'Examens & Contrôles à venir',
    add_reminder: 'Ajouter un rappel',
    title: 'Titre',
    due_date: 'Date d\'échéance',
    type: 'Type',
    assignment: 'Devoir',
    reading: 'Lecture',
    quiz: 'Quiz',
    general: 'Général',
    curriculum_audit: 'Audit du Curriculum',
    ai_auditor: 'Auditeur IA',
    audit_description: "Nous analyserons votre répertoire actuel par rapport aux normes nationales pour {grade} en {country} afin d'identifier les lacunes de connaissances.",
    audit_parameters: 'Paramètres d\'Audit',
    region: 'Région',
    run_deep_audit: 'Lancer l\'Audit Profond',
    suggested_units: 'Unités Suggérées',
    suggested_units_description: "Sur la base du programme pour {grade} en {country}, voici quelques unités suggérées à ajouter à votre répertoire.",
    consulting_resources: 'Consultation des ressources pédagogiques...',
    go_to_classroom: 'Aller à la salle de classe',
    curating_knowledge: 'Curation des connaissances...',
    curating_description: 'Notre IA synthétise les structures pédagogiques et les exigences des examens nationaux pour construire votre unité personnalisée.',
    synthesizing_blocks: 'Synthèse des blocs',
    reset_confirm: 'Êtes-vous sûr de vouloir réinitialiser toutes les données ? Cela ne peut pas être annulé.',
    audit_started: "Audit démarré. Nous vous informerons de toute lacune dans le curriculum.",
    active_paths_desc: 'Vos parcours d\'apprentissage actuellement sélectionnés.',
    profile_setup: 'Configuration du Profil',
    personalize_space: 'Personnalisez votre espace.',
    setup_progress: 'Progression de l\'installation',
    configure_context: 'Configurez votre contexte académique pour permettre la génération de curriculum par IA à partir de ressources mondiales de confiance.',
    academic_region: 'Pôle de Succès Mondial',
    search_countries: 'Rechercher des pays...',
    no_countries_found: 'Aucun pays trouvé',
    ai_adapts: 'Sélectionnez votre région pour vous aligner sur les standards mondiaux.',
    academic_level: 'Votre Niveau de Maîtrise',
    learning_interests: 'Intérêts d\'Apprentissage',
    academic_goal: 'Objectif Académique',
    status: 'Statut',
    settings_saved: 'Paramètres Enregistrés',
    pending_changes: 'Modifications en attente',
    continue_to_classrooms: 'Continuer vers les salles de classe',
    cancel: 'Annuler',
    profile_updated: 'Profil Mis à Jour',
    save_profile: 'Enregistrer le Profil',
    language: 'Chemin vers le Succès',
    select_language: 'Choisissez votre langue pour libérer tout votre potentiel et atteindre l\'excellence.',
    stem: 'STEM',
    humanities: 'Sciences Humaines',
    arts: 'Arts & Design',
    languages: 'Langues',
    tech: 'Technologie',
    exam_prep: 'Préparation aux Examens',
    skill_dev: 'Développement de Compétences',
    general_learning: 'Apprentissage Général',
    career_transition: 'Transition de Carrière',
    grade: 'Définissez votre étape actuelle sur le chemin de l\'excellence.',
    select_session_or_subject: 'Sélectionner une session ou un sujet',
    custom_title: 'Titre personnalisé',
    e_g_math_exam: 'ex: Examen de Maths',
    interactive_learning: 'Apprentissage Interactif',
    triple_click_hint: 'Triple-cliquez sur l\'espace blanc pour déclencher l\'aide IA.',
    hard_questions: '3 Questions Difficiles',
    more_examples: 'Plus d\'Exemples',
    exam_questions: 'Questions d\'Examen',
    generating_interactive: 'L\'IA génère votre contenu personnalisé...',
    interactive_title: 'Support d\'Apprentissage IA',
    interactive_desc: 'Approfondissez votre compréhension avec du contenu généré sur mesure.',
    session_settings: 'Paramètres de Session',
    current_session: 'Session Académique Actuelle',
    default_session_duration: 'Durée d\'Étude par Défaut',
    minutes: 'minutes',
    e_g_fall_2024: 'ex: Automne 2024',
    hero_title: "Arrête de jongler. Construis un système qui fonctionne",
    hero_subtitle: "Ton savoir, enfin organisé",
    hero_cta_primary: "Lance-toi — c'est gratuit",
    hero_cta_secondary: "Laisse l'IA construire pour toi",
    actions_create_levelspace: "Crée ton LevelSpace",
    actions_create_classroom: "Crée une classe",
    actions_generate_ai: "Construis-le avec l'IA",
    actions_track_progress: "Suis ta progression",
    motivation_start_or_stuck: "Commence maintenant. Ne regarde pas en arrière",
    motivation_power: "Ton système. Tes règles",
    onboarding_first_classroom: "Construis ta première classe",
    onboarding_start_building: "Construis ton premier système",
    dashboard_start: "Lance-toi",
    dashboard_continue: "Continue",
    dashboard_explore: "Explore ton espace",
    loading: 'Chargement…',
    classroom_not_found: 'Classe introuvable.',
    classroom_empty_description: 'Chargez les leçons depuis Supabase ou utilisez les suggestions IA.',
    classroom_ai_suggestions: 'Suggestions IA',
  },
  ar: {
    dashboard: 'لوحة القيادة',
    classrooms: 'الفصول الدراسية',
    blueprints: 'المخططات',
    schedule: 'الجدول الزمني',
    progress: 'التقدم',
    library: 'المكتبة',
    settings: 'الإعدادات',
    search: 'بحث...',
    my_space: 'مساحتي',
    active_classrooms: 'الفصول النشطة',
    learning_stats: 'إحصائيات التعلم',
    reminders: 'التذكيرات',
    agenda: 'الأجندة',
    calendar: 'التقويم',
    deep_focus: 'تركيز عميق',
    pomodoro_session: 'جلسة بومودورو',
    start_focus: 'بدء التركيز',
    pause: 'إيقاف مؤقت',
    explore_modules: 'استكشاف الوحدات',
    view_blueprints: 'عرض المخططات',
    academic_repository: 'المستودع الأكاديمي',
    personalized_for: 'مخصص لـ {grade}',
    your_academic_repository: 'مستودعك الأكاديمي.',
    unlock_potential: 'أطلق العنان',
    achieve_greatness: 'لإمكانياتك.',
    manage: 'إدارة',
    no_active_classrooms: 'لا توجد فصول نشطة',
    browse_repository: 'تصفح المستودع',
    run_audit: 'تشغيل التدقيق',
    reset: 'إعادة تعيين',
    preferences: 'التفضيلات',
    active: 'نشط',
    idle: 'خامل',
    modules: 'الوحدات',
    avg_completion: 'متوسط الإكمال',
    view_all: 'عرض الكل',
    no_pending_reminders: 'لا توجد تذكيرات معلقة.',
    no_upcoming_events: 'لا توجد أحداث قادمة.',
    exam: 'امتحان',
    controle: 'مراقبة',
    upcoming_exams: 'الامتحانات والمراقبات القادمة',
    add_reminder: 'إضافة تذكير',
    title: 'العنوان',
    due_date: 'تاريخ الاستحقاق',
    type: 'النوع',
    assignment: 'مهمة',
    reading: 'قراءة',
    quiz: 'اختبار قصير',
    general: 'عام',
    curriculum_audit: 'تدقيق المنهج',
    ai_auditor: 'مدقق الذكاء الاصطناعي',
    audit_description: "سنقوم بتحليل مستودعك الحالي مقابل المعايير الوطنية لـ {grade} في {country} لتحديد فجوات المعرفة.",
    audit_parameters: 'معايير التدقيق',
    region: 'المنطقة',
    run_deep_audit: 'تشغيل التدقيق العميق',
    suggested_units: 'الوحدات المقترحة',
    suggested_units_description: "بناءً على المنهج الدراسي لـ {grade} في {country}، إليك بعض الوحدات المقترحة لإضافتها إلى مستودعك.",
    consulting_resources: 'استشارة الموارد التربوية...',
    go_to_classroom: 'الذهاب إلى الفصل الدراسي',
    curating_knowledge: 'تنسيق المعرفة...',
    curating_description: 'يقوم ذكاؤنا الاصطناعي بتوليف الهياكل التربوية ومتطلبات الامتحانات الوطنية لبناء وحدتك المخصصة.',
    synthesizing_blocks: 'توليف الكتل',
    reset_confirm: 'هل أنت متأكد أنك تريد إعادة تعيين جميع البيانات؟ لا يمكن التراجع عن هذا الإجراء.',
    audit_started: "بدأ التدقيق. سنقوم بإخطارك بأي فجوات في المنهج.",
    active_paths_desc: 'مسارات التعلم المختارة حاليًا.',
    profile_setup: 'إعداد الملف الشخصي',
    personalize_space: 'خصص مساحتك.',
    setup_progress: 'تقدم الإعداد',
    configure_context: 'قم بتكوين سياقك الأكاديمي لتمكين توليد المناهج الدراسية المدعومة بالذكاء الاصطناعي من موارد عالمية موثوقة.',
    academic_region: 'مركز النجاح العالمي',
    search_countries: 'البحث عن الدول...',
    no_countries_found: 'لم يتم العثور على دول',
    ai_adapts: 'اختر منطقتك لتتماشى مع المعايير العالمية المتميزة.',
    academic_level: 'مستوى إتقانك',
    learning_interests: 'اهتمامات التعلم',
    academic_goal: 'الهدف الأكاديمي',
    status: 'الحالة',
    settings_saved: 'تم حفظ الإعدادات',
    pending_changes: 'تغييرات معلقة',
    continue_to_classrooms: 'المتابعة إلى الفصول الدراسية',
    cancel: 'إلغاء',
    profile_updated: 'تم تحديث الملف الشخصي',
    save_profile: 'حفظ الملف الشخصي',
    language: 'طريق النجاح',
    select_language: 'اختر لغتك لإطلاق العنان لإمكانياتك الكاملة وتحقيق العظمة.',
    stem: 'العلوم والتكنولوجيا والهندسة والرياضيات',
    humanities: 'العلوم الإنسانية',
    arts: 'الفنون والتصميم',
    languages: 'اللغات',
    tech: 'التكنولوجيا',
    exam_prep: 'التحضير للامتحانات',
    skill_dev: 'تطوير المهارات',
    general_learning: 'التعلم العام',
    career_transition: 'التحول الوظيفي',
    grade: 'حدد مرحلتك الحالية في طريق التميز.',
    select_session_or_subject: 'اختر الجلسة أو الموضوع',
    custom_title: 'عنوان مخصص',
    e_g_math_exam: 'مثال: امتحان الرياضيات',
    interactive_learning: 'التعلم التفاعلي',
    triple_click_hint: 'انقر ثلاث مرات على المساحة البيضاء لتفعيل دعم الذكاء الاصطناعي.',
    hard_questions: '3 أسئلة صعبة',
    more_examples: 'مزيد من الأمثلة',
    exam_questions: 'أسئلة الامتحان',
    generating_interactive: 'يقوم الذكاء الاصطناعي بإنشاء محتواك المخصص...',
    interactive_title: 'دعم التعلم بالذكاء الاصطناعي',
    interactive_desc: 'عمق فهمك بمحتوى تم إنشاؤه خصيصًا لك.',
    session_settings: 'إعدادات الجلسة',
    current_session: 'الفصل الدراسي الحالي',
    default_session_duration: 'مدة الدراسة الافتراضية',
    minutes: 'دقيقة',
    e_g_fall_2024: 'مثال: خريف 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Use guided setup",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Use guided setup",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
    loading: 'Loading…',
    classroom_not_found: 'Classroom not found.',
    classroom_empty_description: 'Load lessons from Supabase or use guided suggestions.',
    classroom_ai_suggestions: 'Guided suggestions',
  },
  es: {
    dashboard: 'Tablero',
    classrooms: 'Aulas',
    blueprints: 'Planos',
    schedule: 'Horario',
    progress: 'Progreso',
    library: 'Biblioteca',
    settings: 'Ajustes',
    search: 'Buscar...',
    my_space: 'Mi Espacio',
    active_classrooms: 'Aulas Activas',
    learning_stats: 'Estadísticas de Aprendizaje',
    reminders: 'Recordatorios',
    agenda: 'Agenda',
    calendar: 'Calendario',
    deep_focus: 'Enfoque Profundo',
    pomodoro_session: 'Sesión Pomodoro',
    start_focus: 'Iniciar Enfoque',
    pause: 'Pausa',
    explore_modules: 'Explorar Módulos',
    view_blueprints: 'Ver Planos',
    academic_repository: 'Repositorio Académico',
    personalized_for: 'Personalizado para {grade}',
    your_academic_repository: 'Tu Repositorio Académico.',
    unlock_potential: 'Desbloquea tu',
    achieve_greatness: 'potencial.',
    manage: 'Gestionar',
    no_active_classrooms: 'No hay aulas activas',
    browse_repository: 'Explorar Repositorio',
    run_audit: 'Ejecutar Auditoría',
    reset: 'Reiniciar',
    preferences: 'Preferencias',
    active: 'Activo',
    idle: 'Inactivo',
    modules: 'Módulos',
    avg_completion: 'Promedio de Completado',
    view_all: 'Ver todo',
    no_pending_reminders: 'No hay recordatorios pendientes.',
    no_upcoming_events: 'No hay eventos próximos.',
    exam: 'Examen',
    controle: 'Control',
    upcoming_exams: 'Próximos Exámenes y Controles',
    add_reminder: 'Agregar Recordatorio',
    title: 'Título',
    due_date: 'Fecha de Vencimiento',
    type: 'Tipo',
    assignment: 'Tarea',
    reading: 'Lectura',
    quiz: 'Cuestionario',
    general: 'General',
    curriculum_audit: 'Auditoría del Currículo',
    ai_auditor: 'Auditor IA',
    audit_description: "Analizaremos tu repositorio actual frente a los estándares nacionales para {grade} en {country} para identificar brechas de conocimiento.",
    audit_parameters: 'Parámetros de Auditoría',
    region: 'Región',
    run_deep_audit: 'Ejecutar Auditoría Profunda',
    suggested_units: 'Unidades Sugeridas',
    suggested_units_description: "Basado en el currículo para {grade} en {country}, aquí hay algunas unidades sugeridas para agregar a tu repositorio.",
    consulting_resources: 'Consultando recursos pedagógicos...',
    go_to_classroom: 'Ir al Aula',
    curating_knowledge: 'Curando conocimiento...',
    curating_description: 'Nuestra IA está sintetizando estructuras pedagógicas y requisitos de exámenes nacionales para construir tu unidad personalizada.',
    synthesizing_blocks: 'Sintetizando bloques',
    reset_confirm: '¿Estás seguro de que deseas restablecer todos los datos? Esto no se puede deshacer.',
    audit_started: "Auditoría iniciada. Te notificaremos de cualquier brecha en el currículo.",
    active_paths_desc: 'Tus rutas de aprendizaje seleccionadas actualmente.',
    profile_setup: 'Configuración del Perfil',
    personalize_space: 'Personaliza tu espacio.',
    setup_progress: 'Progreso de la configuración',
    configure_context: 'Configura tu contexto académico para permitir la generación de currículos impulsada por IA a partir de recursos globales confiables.',
    academic_region: 'Centro de Éxito Global',
    search_countries: 'Buscar países...',
    no_countries_found: 'No se encontraron países',
    ai_adapts: 'Selecciona tu región para alinearte con los estándares de clase mundial.',
    academic_level: 'Tu Nivel de Maestría',
    learning_interests: 'Intereses de Aprendizaje',
    academic_goal: 'Meta Académica',
    status: 'Estado',
    settings_saved: 'Ajustes Guardados',
    pending_changes: 'Cambios Pendientes',
    continue_to_classrooms: 'Continuar a las aulas',
    cancel: 'Cancelar',
    profile_updated: 'Perfil Actualizado',
    save_profile: 'Guardar Perfil',
    language: 'Camino al Éxito',
    select_language: 'Elige tu idioma para desbloquear todo tu potencial y alcanzar la grandeza.',
    stem: 'STEM',
    humanities: 'Humanidades',
    arts: 'Artes y Diseño',
    languages: 'Idiomas',
    tech: 'Tecnología',
    exam_prep: 'Preparación para Exámenes',
    skill_dev: 'Desarrollo de Habilidades',
    general_learning: 'Aprendizaje General',
    career_transition: 'Transición de Carrera',
    grade: 'Define tu etapa actual en el camino hacia la excelencia.',
    select_session_or_subject: 'Seleccionar sesión o tema',
    custom_title: 'Título personalizado',
    e_g_math_exam: 'ej: Examen de Matemáticas',
    interactive_learning: 'Aprendizaje Interactivo',
    triple_click_hint: 'Haz triple clic en el espacio en blanco para activar el soporte de IA.',
    hard_questions: '3 Preguntas Difíciles',
    more_examples: 'Más Ejemplos',
    exam_questions: 'Preguntas de Examen',
    generating_interactive: 'La IA está generando tu contenido personalizado...',
    interactive_title: 'Soporte de Aprendizaje IA',
    interactive_desc: 'Profundiza tu comprensión con contenido generado a medida.',
    session_settings: 'Ajustes de Sesión',
    current_session: 'Sesión Académica Actual',
    default_session_duration: 'Duración de Estudio por Defecto',
    minutes: 'minutos',
    e_g_fall_2024: 'ej: Otoño 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Use guided setup",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Use guided setup",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
    loading: 'Loading…',
    classroom_not_found: 'Classroom not found.',
    classroom_empty_description: 'Load lessons from Supabase or use guided suggestions.',
    classroom_ai_suggestions: 'Guided suggestions',
  },
  de: {
    dashboard: 'Dashboard',
    classrooms: 'Klassenzimmer',
    blueprints: 'Entwürfe',
    schedule: 'Zeitplan',
    progress: 'Fortschritt',
    library: 'Bibliothek',
    settings: 'Einstellungen',
    search: 'Suche...',
    my_space: 'Mein Bereich',
    active_classrooms: 'Aktive Klassen',
    learning_stats: 'Lernstatistiken',
    reminders: 'Erinnerungen',
    agenda: 'Agenda',
    calendar: 'Kalender',
    deep_focus: 'Tiefer Fokus',
    pomodoro_session: 'Pomodoro-Sitzung',
    start_focus: 'Fokus starten',
    pause: 'Pause',
    explore_modules: 'Module erkunden',
    view_blueprints: 'Entwürfe anzeigen',
    academic_repository: 'Akademisches Repository',
    personalized_for: 'Personalisiert für {grade}',
    your_academic_repository: 'Dein akademisches Repository.',
    unlock_potential: 'Entfalte dein',
    achieve_greatness: 'Potenzial.',
    manage: 'Verwalten',
    no_active_classrooms: 'Keine aktiven Klassen',
    browse_repository: 'Repository durchsuchen',
    run_audit: 'Audit ausführen',
    reset: 'Zurücksetzen',
    preferences: 'Präferenzen',
    active: 'Aktiv',
    idle: 'Inaktiv',
    modules: 'Module',
    avg_completion: 'Durchschn. Abschluss',
    view_all: 'Alle anzeigen',
    no_pending_reminders: 'Keine anstehenden Erinnerungen.',
    no_upcoming_events: 'Keine anstehenden Ereignisse.',
    exam: 'Prüfung',
    controle: 'Kontrolle',
    upcoming_exams: 'Anstehende Prüfungen & Kontrollen',
    add_reminder: 'Erinnerung hinzufügen',
    title: 'Titel',
    due_date: 'Fälligkeitsdatum',
    type: 'Typ',
    assignment: 'Aufgabe',
    reading: 'Lesen',
    quiz: 'Quiz',
    general: 'Allgemein',
    curriculum_audit: 'Lehrplan-Audit',
    ai_auditor: 'KI-Auditor',
    audit_description: "Wir analysieren Ihr aktuelles Repository anhand nationaler Standards für {grade} in {country}, um Wissenslücken zu identifizieren.",
    audit_parameters: 'Audit-Parameter',
    region: 'Region',
    run_deep_audit: 'Tiefen-Audit ausführen',
    suggested_units: 'Vorgeschlagene Einheiten',
    suggested_units_description: "Basierend auf dem Lehrplan für {grade} in {country} sind hier einige vorgeschlagene Einheiten, die Sie Ihrem Repository hinzufügen können.",
    consulting_resources: 'Pädagogische Ressourcen werden konsultiert...',
    go_to_classroom: 'Zum Klassenzimmer',
    curating_knowledge: 'Wissen kuratieren...',
    curating_description: 'Unsere KI synthetisiert pädagogische Strukturen and nationale Prüfungsanforderungen, um Ihre personalisierte Einheit zu erstellen.',
    synthesizing_blocks: 'Blöcke werden synthetisiert',
    reset_confirm: 'Sind Sie sicher, dass Sie alle Daten zurücksetzen möchten? Dies kann nicht rückgängig gemacht werden.',
    audit_started: "Audit gestartet. Wir benachrichtigen Sie über etwaige Lehrplanlücken.",
    active_paths_desc: 'Ihre aktuell ausgewählten Lernpfade.',
    profile_setup: 'Profil-Setup',
    personalize_space: 'Personalisiere deinen Bereich.',
    setup_progress: 'Einrichtungsfortschritt',
    configure_context: 'Konfigurieren Sie Ihren akademischen Kontext, um KI-gesteuerte Lehrplangenerierung aus vertrauenswürdigen globalen Ressourcen zu ermöglichen.',
    academic_region: 'Globales Erfolgszentrum',
    search_countries: 'Länder suchen...',
    no_countries_found: 'Keine Länder gefunden',
    ai_adapts: 'Wählen Sie Ihre Region aus, um sich an erstklassigen Standards auszurichten.',
    academic_level: 'Ihre Meisterschaftsstufe',
    learning_interests: 'Lerninteressen',
    academic_goal: 'Akademisches Ziel',
    status: 'Status',
    settings_saved: 'Einstellungen gespeichert',
    pending_changes: 'Ausstehende Änderungen',
    continue_to_classrooms: 'Weiter zu den Klassenzimmern',
    cancel: 'Abbrechen',
    profile_updated: 'Profil aktualisiert',
    save_profile: 'Profil speichern',
    language: 'Weg zum Erfolg',
    select_language: 'Wählen Sie Ihre Sprache, um Ihr volles Potenzial auszuschöpfen und Großes zu erreichen.',
    stem: 'MINT',
    humanities: 'Geisteswissenschaften',
    arts: 'Kunst & Design',
    languages: 'Sprachen',
    tech: 'Technologie',
    exam_prep: 'Prüfungsvorbereitung',
    skill_dev: 'Kompetenzentwicklung',
    general_learning: 'Allgemeines Lernen',
    career_transition: 'Beruflicher Übergang',
    grade: 'Definieren Sie Ihre aktuelle Etappe auf dem Weg zur Exzellenz.',
    select_session_or_subject: 'Sitzung oder Thema auswählen',
    custom_title: 'Benutzerdefinierter Titel',
    e_g_math_exam: 'z.B. Mathe-Prüfung',
    interactive_learning: 'Interaktives Lernen',
    triple_click_hint: 'Dreifachklick auf den Leerraum, um KI-Unterstützung auszulösen.',
    hard_questions: '3 schwere Fragen',
    more_examples: 'Mehr Beispiele',
    exam_questions: 'Prüfungsfragen',
    generating_interactive: 'KI generiert Ihre benutzerdefinierten Inhalte...',
    interactive_title: 'KI-Lernunterstützung',
    interactive_desc: 'Vertiefen Sie Ihr Verständnis mit maßgeschneiderten Inhalten.',
    session_settings: 'Sitzungseinstellungen',
    current_session: 'Aktuelle akademische Sitzung',
    default_session_duration: 'Standard-Studiendauer',
    minutes: 'Minuten',
    e_g_fall_2024: 'z.B. Herbst 2024',
    hero_title: "Stop juggling. Build a system that works",
    hero_subtitle: "Your knowledge, finally organized",
    hero_cta_primary: "Start building — it's free",
    hero_cta_secondary: "Use guided setup",
    actions_create_levelspace: "Create your LevelSpace",
    actions_create_classroom: "Create a classroom",
    actions_generate_ai: "Use guided setup",
    actions_track_progress: "See your progress",
    motivation_start_or_stuck: "Start now. Don't look back",
    motivation_power: "Your system. Your rules",
    onboarding_first_classroom: "Build your first classroom",
    onboarding_start_building: "Build your first system",
    dashboard_start: "Start building",
    dashboard_continue: "Keep going",
    dashboard_explore: "Explore your space",
    loading: 'Loading…',
    classroom_not_found: 'Classroom not found.',
    classroom_empty_description: 'Load lessons from Supabase or use guided suggestions.',
    classroom_ai_suggestions: 'Guided suggestions',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
